#!/usr/bin/env python3
"""
setup_survey.py

Build the classical single-point survey: every ring, every roll, a water walked
through on a straight line, so that a representative per size can be chosen from
the distribution of barriers rather than from a geometric proxy.

How the frames are driven
-------------------------
Not as files. Writing every frame out would mean ~150,000 data files for a full
survey, and a read_data for each one. Instead each case - one ring at one roll -
gets a single starting structure with the water at the far end of its path, and
LAMMPS walks it through with displace_atoms between `run 0` calls. That is one
read_data and n_frames single points per case, and about thirty times fewer
files.

generate_ring_path.py still writes explicit frames, and is the thing to use for
spot checks and for handing geometries to VASP. This script is for the sweep.

How the work is split
---------------------
Not with MPI. These clusters are 18 to 48 atoms; handing one to 64 ranks leaves
most of them holding no atoms at all. The survey is instead embarrassingly
parallel over cases, so the case list is split into `--shards` shards and each
shard is run by its own serial LAMMPS. The generated submit script starts them
together and waits.

Output
------
  <outdir>/data/<ring>__roll_<deg>.data   one starting structure per case
  <outdir>/shards/<k>/*.txt               the per-shard case lists, as the
                                          parallel files LAMMPS reads with
                                          `variable ... file`
  <outdir>/in.survey                      the LAMMPS input, same for every shard
  <outdir>/submit_survey.slurm            starts one serial LAMMPS per shard
  <outdir>/cases.csv                      the python-side record of every case,
                                          which collect_survey.py joins the
                                          energies back onto
"""

from __future__ import annotations

import argparse
import csv
import os
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "water_path"))
import lammps_data as ld  # noqa: E402
from generate_ring_path import axis_positions, required_half_length  # noqa: E402
from ring_geometry import nearest_distance_fn  # noqa: E402
from water_geometry import resolve_offsets  # noqa: E402
from water_placement import apply_water_types, build_frame  # noqa: E402

DEFAULT_ROLLS = (0.0, 30.0, 60.0, 90.0, 120.0, 150.0)

# Atom types, fixed by the element order on the pair_coeff line in pot.mod:
#   pair_coeff * * SiOH.usc Si O H
# The water oxygen is an ordinary type 2; the hydrogens are type 3, which the
# cluster files do not define until apply_water_types adds its Masses row.
SI_TYPE, O_TYPE, H_TYPE = 1, 2, 3

# The parallel per-shard lists LAMMPS walks with `variable <name> file`. One
# line per case, advanced together by a single `next`.
CASE_FILES = ("data", "label", "dx", "dy", "dz", "nframes", "nfix")

CASE_COLUMNS = [
    "case_id", "ring_id", "n", "roll", "half_length", "n_frames", "step",
    "nfix", "o_id", "h1_id", "h2_id", "shard", "data_file",
    "reference_separation", "min_separation",
]

IN_SURVEY = """\
# Ring-permeation single-point survey, generated by setup_survey.py
#
# One case per line of the shard's parallel lists: a ring at one roll, with the
# water parked at the far end of its path. The inner loop is n_frames of
# `run 0`, stepping the water along the axis with displace_atoms in between, so
# the whole path costs one read_data.
#
# Nothing is minimised. The substrate never moves and the water is rigid, so the
# difference between two frames is a pure interaction energy; the first frame is
# far enough out to be non-interacting and serves as the reference.
#
# Run as:  lmp -in in.survey -var shard 000 -var out energies_000.txt

variable data    file @PREFIX@shards/${shard}/data.txt
variable label   file @PREFIX@shards/${shard}/label.txt
variable dx      file @PREFIX@shards/${shard}/dx.txt
variable dy      file @PREFIX@shards/${shard}/dy.txt
variable dz      file @PREFIX@shards/${shard}/dz.txt
variable nframes file @PREFIX@shards/${shard}/nframes.txt
variable nfix    file @PREFIX@shards/${shard}/nfix.txt

shell rm -f ${out}

label nextcase

clear
units           metal
dimension       3
boundary        p p p
atom_style      atomic

read_data       ${data}
include         pot.mod

# The water is the three atoms appended after every cluster atom, so it is the
# tail of the id range. nfix is that cluster maximum, written per case. If that
# ever stops being true the energies would still look plausible, so check it
# rather than trust it.
group           water id > ${nfix}
if "$(count(water)) != 3" then &
  "print 'FATAL: water group holds $(count(water)) atoms in ${label}, expected 3'" &
  "quit 1"

thermo_style    custom step pe
thermo          1
# metal units already default to un-normalised energies; say so anyway, because
# a per-atom pe would rescale every barrier without looking wrong.
thermo_modify   norm no

variable f loop ${nframes}
label nextframe

# `pre yes` is the default and is what recomputes forces after the atoms moved;
# do not turn it off. The same number also lands in the log through thermo, so
# the log is a cross-check on this print rather than a duplicate.
run 0 post no
print "${label} ${f} $(pe:%.12g)" append ${out} screen no
displace_atoms water move ${dx} ${dy} ${dz} units box

next f
jump SELF nextframe

next data label dx dy dz nframes nfix
jump SELF nextcase

print "shard ${shard} finished"
"""

SUBMIT = """\
#!/bin/bash
#SBATCH --account=priyav_216
#SBATCH --nodes=1
#SBATCH --ntasks={shards}
#SBATCH --partition=priya
#SBATCH --time={walltime}
#SBATCH --mem=0
#SBATCH --exclusive
#SBATCH --output=STREAM_OUTPUT
#SBATCH --job-name=ring-survey
#SBATCH --constraint=epyc-7513
#SBATCH --mail-type=all
#SBATCH --mail-user=lkyamamo@usc.edu
ulimit -s unlimited
echo "starting survey **************************************"
date

############################
# Paths
#
# Same convention as the other runs: canonical inputs live in ../input_files/
# and are symlinked into the run directory so LAMMPS resolves the same
# basenames (pot.mod, SiOH.usc) with cwd here.
############################

RUN_DIR=$SLURM_SUBMIT_DIR
INPUT_DIR="$(cd "$RUN_DIR/../input_files" && pwd)"

export lmp="/home1/lkyamamo/executables/lammps/lmp_mpi_2019"

cd "$RUN_DIR"
shopt -s nullglob
for entry in "$INPUT_DIR"/*; do
  ln -sfn "$entry" "$(basename "$entry")"
done
shopt -u nullglob

module purge
module load usc
module load fftw

############################
# Run
#
# One serial LAMMPS per shard, all at once. These clusters are a few dozen
# atoms, so MPI-decomposing a single one is pointless - the parallelism is
# across cases.
############################

for shard in {shard_list}; do
  $lmp -log log_${{shard}}.lammps \\
       -in in.survey \\
       -var shard ${{shard}} \\
       -var out energies_${{shard}}.txt &
done
wait

cat energies_*.txt > energies.txt
wc -l energies.txt

date
echo "survey finished **************************************"
exit 0
"""


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--clusters", required=True,
                        help="the cluster directory from build_ring_cluster.py")
    parser.add_argument("--manifest", default=None,
                        help="cluster_manifest.csv (default: <clusters>/cluster_manifest.csv)")
    parser.add_argument("--outdir", required=True,
                        help="where the generated structures and shard lists go. Under "
                             "this project's convention that is <case>/setup/survey, which "
                             "LAMMPS reaches from the run directory as ../setup/survey")
    parser.add_argument("--input-dir", default=None,
                        help="where in.survey goes, alongside pot.mod and the potential "
                             "(the convention: <case>/input_files). Defaults to --outdir")
    parser.add_argument("--run-dir", default=None,
                        help="the directory LAMMPS will run in, which is where the submit "
                             "script goes (<case>/run). Every path inside in.survey is "
                             "written relative to it. Defaults to --outdir")
    parser.add_argument("--h-rotation", nargs="+", type=float, default=list(DEFAULT_ROLLS),
                        help=f"rolls in degrees (default: {' '.join(f'{r:g}' for r in DEFAULT_ROLLS)})")
    parser.add_argument("--n-steps", type=int, default=28,
                        help="steps along each path; n+1 frames (default: 28)")
    parser.add_argument("--orientation", choices=("away", "toward", "perpendicular"),
                        default="away", help="which way the hydrogens face (default: away)")
    parser.add_argument("--oh-length", type=float, default=0.9572)
    parser.add_argument("--hoh-angle", type=float, default=104.52)
    parser.add_argument("--min-endpoint-separation", type=float, default=5.5,
                        help="the first frame must have every water atom at least this far "
                             "from the cluster, so it is a valid energy reference "
                             "(default: 5.5, the USC two-body cutoff)")
    parser.add_argument("--shards", type=int, default=64,
                        help="how many serial LAMMPS processes to split the cases over "
                             "(default: 64)")
    parser.add_argument("--walltime", default="02:00:00")
    parser.add_argument("--size", type=int, action="append", default=None,
                        help="only rings of this size (repeatable)")
    parser.add_argument("--limit", type=int, default=None,
                        help="only the first N rings, for a trial run")
    return parser.parse_args(argv)


def main(argv=None) -> int:
    args = parse_args(argv)
    clusters = Path(args.clusters)
    manifest = Path(args.manifest) if args.manifest else clusters / "cluster_manifest.csv"
    outdir = Path(args.outdir)

    with open(manifest) as handle:
        catalogue = list(csv.DictReader(handle))
    if args.size:
        sizes = set(args.size)
        catalogue = [r for r in catalogue if int(r["n"]) in sizes]
    if args.limit:
        catalogue = catalogue[:args.limit]
    if not catalogue:
        raise ValueError("no rings selected")

    rolls = list(args.h_rotation)
    n_frames = args.n_steps + 1
    print(f"{len(catalogue)} rings x {len(rolls)} rolls x {n_frames} frames = "
          f"{len(catalogue) * len(rolls) * n_frames} single points")

    (outdir / "data").mkdir(parents=True, exist_ok=True)
    run_root = Path(args.run_dir) if args.run_dir else outdir
    run_root.mkdir(parents=True, exist_ok=True)
    prefix = os.path.relpath(outdir, run_root)
    prefix = "" if prefix == "." else prefix.rstrip("/") + "/"
    if prefix:
        print(f"paths inside in.survey are relative to {run_root}/ -> {prefix}")
    cases: list[dict] = []

    for count, entry in enumerate(catalogue, start=1):
        cluster_file = clusters / entry["file"]
        center = np.array([float(entry[f"center_{a}"]) for a in "xyz"])
        axis = np.array([float(entry[f"axis_{a}"]) for a in "xyz"])
        axis = axis / np.linalg.norm(axis)

        base, style = ld.load(str(cluster_file), quiet=True)
        nfix = int(base.atoms.index.max())
        apply_water_types(base)   # registers the type 3 mass, so the file has 3 types

        offsets = {roll: resolve_offsets(
            axis, orientation=args.orientation, h_rotation=roll,
            oh_length=args.oh_length, hoh_angle=args.hoh_angle)[:2] for roll in rolls}

        # One half-length for the whole ring, clearing the cutoff for every roll,
        # so the rolls stay directly comparable frame for frame.
        nearest = nearest_distance_fn(
            base.atoms[["x", "y", "z"]].to_numpy(dtype=float), ld.box_lengths(base))
        half_length = required_half_length(
            nearest, center, axis, list(offsets.values()), args.min_endpoint_separation)
        along = axis_positions(half_length, args.n_steps)
        step = (along[1] - along[0]) * axis

        for roll in rolls:
            h1, h2 = offsets[roll]
            oxygen = center + along[0] * axis
            positions = {"O": oxygen, "H1": oxygen + h1, "H2": oxygen + h2}
            frame, ids, _, _ = build_frame(
                base, positions, O_TYPE, H_TYPE,
                {"O": 0.0, "H1": 0.0, "H2": 0.0}, 0, "start")

            case_id = f"{entry['ring_id'].replace('/', '__')}__roll_{int(round(roll)) % 360:03d}"
            data_file = outdir / "data" / f"{case_id}.data"
            ld.write_data_file(
                frame, str(data_file),
                f"ring-permeation survey start frame: {entry['ring_id']}, roll {roll:g} deg, "
                f"water at {along[0]:+.4f} A on the axis",
                style)

            reference = float(nearest(np.array(list(positions.values()))).min())
            walk = np.array([oxygen + s * axis + d
                             for s in np.linspace(0, along[-1] - along[0], n_frames)
                             for d in (np.zeros(3), h1, h2)])
            tightest = float(nearest(walk).min())

            cases.append({
                "case_id": case_id, "ring_id": entry["ring_id"], "n": entry["n"],
                "roll": roll, "half_length": round(half_length, 4),
                "n_frames": n_frames, "step": round(float(along[1] - along[0]), 6),
                "nfix": nfix, "o_id": ids["O"], "h1_id": ids["H1"], "h2_id": ids["H2"],
                "shard": "", "data_file": str(Path("data") / f"{case_id}.data"),
                "_lammps_path": prefix + str(Path("data") / f"{case_id}.data"),
                "reference_separation": round(float(reference), 4),
                "min_separation": round(float(tightest), 4),
                "_dx": step[0], "_dy": step[1], "_dz": step[2],
            })

        if count % 50 == 0 or count == len(catalogue):
            print(f"\r  prepared {count}/{len(catalogue)} rings", end="", flush=True)
    print()

    bad = [c for c in cases if c["reference_separation"] < args.min_endpoint_separation]
    if bad:
        raise ValueError(
            f"{len(bad)} case(s) start inside {args.min_endpoint_separation} A of the "
            f"cluster, so their reference frame is not free; first is {bad[0]['case_id']} "
            f"at {bad[0]['reference_separation']} A")

    # Shard round-robin rather than in blocks, so every shard gets a mix of ring
    # sizes and they finish at about the same time.
    shards = max(1, min(args.shards, len(cases)))
    for index, case in enumerate(cases):
        case["shard"] = f"{index % shards:03d}"

    for shard in range(shards):
        members = [c for c in cases if c["shard"] == f"{shard:03d}"]
        shard_dir = outdir / "shards" / f"{shard:03d}"
        shard_dir.mkdir(parents=True, exist_ok=True)
        columns = {
            "data": [c["_lammps_path"] for c in members],
            "label": [f"{c['case_id']}" for c in members],
            "dx": [f"{c['_dx']:.10f}" for c in members],
            "dy": [f"{c['_dy']:.10f}" for c in members],
            "dz": [f"{c['_dz']:.10f}" for c in members],
            "nframes": [str(c["n_frames"]) for c in members],
            "nfix": [str(c["nfix"]) for c in members],
        }
        for name in CASE_FILES:
            (shard_dir / f"{name}.txt").write_text("\n".join(columns[name]) + "\n")

    # LAMMPS runs with the run directory as cwd, so everything it opens - the
    # shard lists and the structures named inside them - is written relative to
    # that, not to wherever this script was pointed.
    input_dir = Path(args.input_dir) if args.input_dir else outdir
    run_dir = Path(args.run_dir) if args.run_dir else outdir
    input_dir.mkdir(parents=True, exist_ok=True)
    run_dir.mkdir(parents=True, exist_ok=True)

    (input_dir / "in.survey").write_text(IN_SURVEY.replace("@PREFIX@", prefix))
    (run_dir / "submit_survey.slurm").write_text(SUBMIT.format(
        shards=shards, walltime=args.walltime,
        shard_list=" ".join(f"{s:03d}" for s in range(shards))))

    with open(outdir / "cases.csv", "w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=CASE_COLUMNS, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(cases)

    lengths = np.array([c["half_length"] for c in cases])
    print(f"\nhalf-length solved per ring: median {np.median(lengths):.2f} A, "
          f"range {lengths.min():.2f}-{lengths.max():.2f} A")
    print(f"tightest approach on the path: median {np.median([c['min_separation'] for c in cases]):.2f} A")
    print(f"{len(cases)} cases over {shards} shards "
          f"({len(cases) // shards}-{-(-len(cases) // shards)} each)")
    print(f"\nwrote {outdir}/")
    print(f"  pot.mod and SiOH.usc must resolve from the run directory - the submit "
          f"script symlinks them from ../input_files/ as the other runs do")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (ValueError, KeyError, OSError) as error:
        sys.exit(f"setup_survey.py: {error}")
