#!/usr/bin/env python3
"""
generate_lammps_script.py

Write a LAMMPS input script that carves a spherical bubble out of a
silica/water data file.  Exits after writing the script — does not
invoke LAMMPS.  LAMMPS is called by the orchestrating run_bubble.sh.

Usage:
    python3 generate_lammps_script.py \\
        --input  system.data \\
        --output system_bubble.data \\
        --script bubble.in \\
        --cx 400.0 --cy 400.0 --cz 881.0 \\
        --radius 150.0 \\
        [--atom-style atomic]
"""

from __future__ import annotations

import argparse
from pathlib import Path


def _bubble_regions(cx: float, cy: float, cz: float, radius: float) -> str:
    """
    Return LAMMPS region commands defining:
        'bubble'         — sphere (side in)
        'outside_bubble' — sphere (side out)
    """
    return "\n".join([
        f"region bubble         sphere {cx} {cy} {cz} {radius} side in",
        f"region outside_bubble sphere {cx} {cy} {cz} {radius} side out",
    ])


def generate_script(
    input_file: str,
    output_file: str,
    cx: float,
    cy: float,
    cz: float,
    radius: float,
    atom_style: str,
) -> str:
    """Return the full LAMMPS input script as a string."""
    lines = [
        "# Generated by generate_lammps_script.py — do not edit by hand",
        "",
        f"atom_style {atom_style}",
        "",
        f"read_data {input_file}",
        "",
        "# ── bubble region ─────────────────────────────────────────────",
        _bubble_regions(cx, cy, cz, radius),
        "",
        "# ── delete atoms inside bubble (mol no: atom_style atomic has no",
        "# ── molecule IDs; orphan cleanup is handled by cleanup_orphan_atoms.py)",
        "delete_atoms region bubble mol no",
        "",
        "# ── write result ──────────────────────────────────────────────",
        f"write_data {output_file}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a LAMMPS input script to carve a spherical bubble."
    )
    parser.add_argument("--input",      required=True, help="Input LAMMPS data file")
    parser.add_argument("--output",     required=True, help="Output LAMMPS data file written by LAMMPS")
    parser.add_argument("--script",     required=True, help="Path to write the generated .in script")
    parser.add_argument("--cx",         required=True, type=float, help="Bubble centre x (Å)")
    parser.add_argument("--cy",         required=True, type=float, help="Bubble centre y (Å)")
    parser.add_argument("--cz",         required=True, type=float, help="Bubble centre z (Å)")
    parser.add_argument("--radius",     required=True, type=float, help="Bubble radius (Å)")
    parser.add_argument("--atom-style", default="atomic", help="LAMMPS atom_style (default: atomic)")
    args = parser.parse_args()

    script = generate_script(
        input_file=args.input,
        output_file=args.output,
        cx=args.cx,
        cy=args.cy,
        cz=args.cz,
        radius=args.radius,
        atom_style=args.atom_style,
    )

    script_path = Path(args.script)
    script_path.write_text(script)
    print(f"LAMMPS script written to: {script_path}")


if __name__ == "__main__":
    main()
